// Generated by scripts/generate-autocomplete.mjs. Do not edit by hand.

export type GeneratedArduinoKeyword = {
  name: string
  library: string
  tokenType: string
}

export const generatedArduinoKeywords: GeneratedArduinoKeyword[] = [
  {
    "name": "abs8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "add8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "addLeds",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "APA102",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "APA104",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "APA106",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "AppendDescriptor",
    "library": "HID",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "applyGamma_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "attach",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "attached",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "autoscroll",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "available",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "BACKWARD_HUES",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "beat16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beat8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beat88",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beatsin16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beatsin8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beatsin88",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "HID",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "begin",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "beginTransmission",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "BGR",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "BlackLightFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "blend",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "blend8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "blink",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "BRG",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "brighten8_lin",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "brighten8_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "brighten8_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "bseconds16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "Candle",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "capacitiveSensor",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CapacitiveSensor",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "capacitiveSensorRaw",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CarbonArc",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "CFastLED",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CHSV",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CHSVPalette16",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CHSVPalette256",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "cleanup_R1",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "clear",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "clear",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ClearBlueSky",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "clearData",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CLEDController",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "close",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CloudColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "ColorFromPalette",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CoolWhiteFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "cos16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "cos8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "countFPS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "createChar",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CRGB::AliceBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Amethyst",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::AntiqueWhite",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Aqua",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Aquamarine",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Azure",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Beige",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Bisque",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Black",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::BlanchedAlmond",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Blue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::BlueViolet",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Brown",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::BurlyWood",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::CadetBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Chartreuse",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Chocolate",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Coral",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::CornflowerBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Cornsilk",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Crimson",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Cyan",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkCyan",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkGoldenrod",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkGray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkKhaki",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkMagenta",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkOliveGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkOrange",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkOrchid",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkRed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkSalmon",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkSeaGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkSlateBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkSlateGray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkSlateGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkTurquoise",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DarkViolet",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DeepPink",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DeepSkyBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DimGray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DimGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::DodgerBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::FairyLight",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::FairyLightNCC",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::FireBrick",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::FloralWhite",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::ForestGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Fuchsia",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Gainsboro",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::GhostWhite",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Gold",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Goldenrod",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Gray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Green",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::GreenYellow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Grey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Honeydew",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::HotPink",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::IndianRed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Indigo",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Ivory",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Khaki",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Lavender",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LavenderBlush",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LawnGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LemonChiffon",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightCoral",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightCyan",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightGoldenrodYellow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightPink",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSalmon",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSeaGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSkyBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSlateGray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSlateGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightSteelBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LightYellow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Lime",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::LimeGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Linen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Magenta",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Maroon",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumAquamarine",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumOrchid",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumPurple",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumSeaGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumSlateBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumSpringGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumTurquoise",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MediumVioletRed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MidnightBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MintCream",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::MistyRose",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Moccasin",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::NavajoWhite",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Navy",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::OldLace",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Olive",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::OliveDrab",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Orange",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::OrangeRed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Orchid",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PaleGoldenrod",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PaleGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PaleTurquoise",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PaleVioletRed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PapayaWhip",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PeachPuff",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Peru",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Pink",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Plaid",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Plum",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::PowderBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Purple",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Red",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::RosyBrown",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::RoyalBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SaddleBrown",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Salmon",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SandyBrown",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SeaGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Seashell",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Sienna",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Silver",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SkyBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SlateBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SlateGray",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SlateGrey",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Snow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SpringGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::SteelBlue",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Tan",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Teal",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Thistle",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Tomato",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Turquoise",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Violet",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Wheat",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::White",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::WhiteSmoke",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::Yellow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGB::YellowGreen",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "CRGBArray",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CRGBPalette16",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "CRGBPalette256",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "cubicwave8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "cursor",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "DEFINE_GRADIENT_PALETTE",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "detach",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "dim8_lin",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "dim8_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "dim8_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "direction",
    "library": "Stepper",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "DirectSunlight",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "display",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "DMXSERIAL",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "DMXSIMPLE",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "DOTSTAR",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "ease16InOutApprox",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ease16InOutCubic",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ease16InOutQuad",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ease8InOutApprox",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ease8InOutCubic",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ease8InOutQuad",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EEPROM",
    "library": "EEPROM",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "EEPtr",
    "library": "EEPROM",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EERef",
    "library": "EEPROM",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "end",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "end",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "endTransmission",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_BSECONDS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_BSECONDS_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_HOURS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_HOURS_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MILLIS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MILLIS_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MILLISECONDS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MILLISECONDS_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MINUTES",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_MINUTES_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_SECONDS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "EVERY_N_SECONDS_I",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "exists",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fade_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fade_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fadeLightBy",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fadeToBlackBy",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "FastLED",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "FastPin",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "FastSPI",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "FastSPI_LED2",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "File",
    "library": "SD",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "FILE_READ",
    "library": "SD",
    "tokenType": "LITERAL1"
  },
  {
    "name": "FILE_WRITE",
    "library": "SD",
    "tokenType": "LITERAL1"
  },
  {
    "name": "fill_2dnoise16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_2dnoise8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_gradient",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_gradient_RGB",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_noise16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_noise8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_palette",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_palette_circular",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_rainbow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_rainbow_circular",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_raw_2dnoise16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_raw_2dnoise16into8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_raw_2dnoise8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_raw_noise16into8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_raw_noise8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "fill_solid",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "flush",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "ForestColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "FORWARD_HUES",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "FullSpectrumFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GBR",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GE8822",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "getBrightness",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "getFPS",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "GRB",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GrowLightFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GS1903",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GW6205",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GW6205_400",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "GW6205B",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "Halogen",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HeatColor",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "HeatColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HID",
    "library": "HID",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "HID_TX",
    "library": "HID",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HighNoonSun",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HighPressureSodium",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "home",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "hours8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "hsv2grb_rainbow",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "hsv2rgb_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "hsv2rgb_spectrum",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "HUE_AQUA",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_BLUE",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_GREEN",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_ORANGE",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_PINK",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_PURPLE",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_RED",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "HUE_YELLOW",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "inoise16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "inoise16_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "inoise8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "inoise8_raw",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "isListening",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "LavaColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LEDS",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "leftToRight",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "lerp15by16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "lerp15by8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "lerp16by16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "lerp16by8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "lerp8by8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "LINEARBLEND",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LiquidCrystal",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "listen",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "LONGEST_HUES",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LPD1886",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LPD1886_8BIT",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LPD6803",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "LPD8806",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "map_data_into_colors_through_palette",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "map8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "MercuryVapor",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "MetalHalide",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "minutes16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "mkdir",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "mul8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "napplyGamma_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nblend",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "NEOPIXEL",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "noAutoscroll",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "NOBLEND",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "noBlink",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "noCursor",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "noDisplay",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8x2",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8x2_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8x3",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "nscale8x3_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "OceanColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "OCTOWS2811",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "OCTOWS2811_400",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "OCTOWS2813",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "onReceive",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "onRequest",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "open",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "OvercastSky",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "overflow",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "P9813",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "PartyColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "peek",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "PingUnit",
    "library": "StudioSonar",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "PingUnit::CENTIMETERS",
    "library": "StudioSonar",
    "tokenType": "LITERAL1"
  },
  {
    "name": "PingUnit::INCHES",
    "library": "StudioSonar",
    "tokenType": "LITERAL1"
  },
  {
    "name": "PingUnit::MICROSECONDS",
    "library": "StudioSonar",
    "tokenType": "LITERAL1"
  },
  {
    "name": "PIXIE",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "PL9823",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "position",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "print",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "qadd7",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "qadd8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "qmul8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "qsub8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "quadwave8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "Rainbow_gp",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "RainbowColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "RainbowStripeColors_p",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "random16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "random16_add_entropy",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "random16_get_seed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "random16_set_seed",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "random8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "RBG",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "read",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "read",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "readMicroseconds",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "remove",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "requestFrom",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "reset_CS_AutoCal",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "RGB",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "rightToLeft",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "rmdir",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scale16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scale16by8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scale8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scale8_video",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scrollDisplayLeft",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "scrollDisplayRight",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "SD",
    "library": "SD",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "SDFile",
    "library": "SD",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "seconds16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "seek",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "SendReport",
    "library": "HID",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "Servo",
    "library": "Servo",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "set_CS_AutocaL_Millis",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "set_CS_Timeout_Millis",
    "library": "CapacitiveSensor",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setBitOrder",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setBrightness",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setClock",
    "library": "Wire",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setClockDivider",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setCorrection",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setCursor",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setDataMode",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setDither",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setMaxPowerInMilliWatts",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setMaxPowerInVoltsAndMilliamps",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setMaxRefreshRate",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setRowOffsets",
    "library": "LiquidCrystal",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setSpeed",
    "library": "Stepper",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "setTemperature",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "SHORTEST_HUES",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "show",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "showColor",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "showLeds",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "sin16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "sin16_avr",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "sin8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "size",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "size",
    "library": "SD",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "SK6812",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SK6822",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SK9822",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SM16703",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SM16716",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SMART_MATRIX",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SodiumVapor",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SoftwareSerial",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "sonar",
    "library": "StudioSonar",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "Sonar",
    "library": "StudioSonar",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "Sonar::ping",
    "library": "StudioSonar",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "speed",
    "library": "Stepper",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "SPI",
    "library": "SPI",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "SPI_CLOCK_DIV128",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV16",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV2",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV32",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV4",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV64",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_CLOCK_DIV8",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_MODE0",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_MODE1",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_MODE2",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "SPI_MODE3",
    "library": "SPI",
    "tokenType": "LITERAL1"
  },
  {
    "name": "sqrt16",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "StandardFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "step",
    "library": "Stepper",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "Stepper",
    "library": "Stepper",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "sub8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "TBlendType",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TDynamicRGBGradientPalette_byte",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TDynamicRGBGradientPalette_bytes",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TDynamicRGBGradientPaletteRef",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TM1803",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TM1804",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TM1809",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TM1812",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TM1829",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TProgmemHSVPalette16",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemHSVPalette32",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemPalette16",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemPalette32",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemRGBGradientPalette_byte",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemRGBGradientPalette_bytes",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemRGBGradientPaletteRef",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemRGBPalette16",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "TProgmemRGBPalette32",
    "library": "FastLED",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "transfer",
    "library": "SPI",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "triwave8",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "Tungsten100W",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "Tungsten40W",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "Typical8mmPixel",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TypicalLEDStrip",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TypicalPixelString",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "TypicalSMD5050",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UCS1903",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UCS1903B",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UCS1904",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UCS2903",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UncorrectedColor",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "UncorrectedTemperature",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "update",
    "library": "EEPROM",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "UpscalePalette",
    "library": "FastLED",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "version",
    "library": "Stepper",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "WarmFluorescent",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "Wire",
    "library": "Wire",
    "tokenType": "KEYWORD1"
  },
  {
    "name": "write",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "write",
    "library": "SoftwareSerial",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "writeMicroseconds",
    "library": "Servo",
    "tokenType": "KEYWORD2"
  },
  {
    "name": "WS2801",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2803",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2811",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2811_400",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2812",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2812B",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2812SERIAL",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2813",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  },
  {
    "name": "WS2852",
    "library": "FastLED",
    "tokenType": "LITERAL1"
  }
]

export const generatedArduinoHeaders = [
  "Arduino.h",
  "CapacitiveSensor.h",
  "EEPROM.h",
  "FastLED.h",
  "HID.h",
  "LiquidCrystal.h",
  "SD.h",
  "SPI.h",
  "Servo.h",
  "SoftwareSerial.h",
  "Stepper.h",
  "StudioSonar.h",
  "Wire.h"
] as const
